=begin
#DHL eCommerce's Duty and Tax Calculator

#DHL eCommerce’s Duty and Tax Calculator API calculates the total cost of a cross-border shipment. Fully Landed Costs are the total amount of costs of a cross border purchase including the price of the goods, shipping costs, customs duties, taxes, insurance, currency conversion, transaction fees, and any other service fees that might occur.  <strong><span style=\"color:#d40511;\">Note:</span></strong> The \"Try now!\" feature on this page is being finalized and will be available in the upcoming weeks. Nevertheless, The API is available and can be used by any client application (e.g. cURL, Postman, etc).

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'

# Unit tests for DhlEcommerceClient::AuthorizationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AuthorizationApi' do
  before do
    # run before each test
    @instance = DhlEcommerceClient::AuthorizationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthorizationApi' do
    it 'should create an instance of AuthorizationApi' do
      expect(@instance).to be_instance_of(DhlEcommerceClient::AuthorizationApi)
    end
  end

  # unit tests for account_v1_auth_accesstoken_get
  # Get Access Token
  # The Get Access Token API call provides an OAuth 2.0 Bearer token with authorization scope, assigned to your client id, which will grant you access to the Global DHL eCommerce APIs. More details about it can be foud &lt;a href&#x3D;\&quot;/api-reference/duty-and-tax-calculator#get-started-section/user-guide%authorization\&quot;&gt;here&lt;/a&gt;
  # @param accept
  # @param [Hash] opts the optional parameters
  # @return [GetAccessTokenresponse]
  describe 'account_v1_auth_accesstoken_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
