=begin
#DHL eCommerce's Duty and Tax Calculator

#DHL eCommerce’s Duty and Tax Calculator API calculates the total cost of a cross-border shipment. Fully Landed Costs are the total amount of costs of a cross border purchase including the price of the goods, shipping costs, customs duties, taxes, insurance, currency conversion, transaction fees, and any other service fees that might occur.  <strong><span style=\"color:#d40511;\">Note:</span></strong> The \"Try now!\" feature on this page is being finalized and will be available in the upcoming weeks. Nevertheless, The API is available and can be used by any client application (e.g. cURL, Postman, etc).

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

# Common files
require 'dhl_ecommerce_client/api_client'
require 'dhl_ecommerce_client/api_error'
require 'dhl_ecommerce_client/version'
require 'dhl_ecommerce_client/configuration'

# Models
require 'dhl_ecommerce_client/models/area'
require 'dhl_ecommerce_client/models/consignee_address'
require 'dhl_ecommerce_client/models/customs_detail'
require 'dhl_ecommerce_client/models/customs_detail1'
require 'dhl_ecommerce_client/models/fee_total'
require 'dhl_ecommerce_client/models/freight_charge'
require 'dhl_ecommerce_client/models/freight_charge1'
require 'dhl_ecommerce_client/models/get_access_tokenresponse'
require 'dhl_ecommerce_client/models/height'
require 'dhl_ecommerce_client/models/insurance_charge'
require 'dhl_ecommerce_client/models/insurance_charge1'
require 'dhl_ecommerce_client/models/item_fee'
require 'dhl_ecommerce_client/models/item_freight'
require 'dhl_ecommerce_client/models/item_freight1'
require 'dhl_ecommerce_client/models/item_insurance'
require 'dhl_ecommerce_client/models/item_insurance1'
require 'dhl_ecommerce_client/models/item_quantity'
require 'dhl_ecommerce_client/models/item_value'
require 'dhl_ecommerce_client/models/item_value1'
require 'dhl_ecommerce_client/models/length'
require 'dhl_ecommerce_client/models/package_details'
require 'dhl_ecommerce_client/models/package_details1'
require 'dhl_ecommerce_client/models/package_fee'
require 'dhl_ecommerce_client/models/product_identifiers'
require 'dhl_ecommerce_client/models/request_quote400response'
require 'dhl_ecommerce_client/models/request_quoterequest'
require 'dhl_ecommerce_client/models/request_quoteresponse'
require 'dhl_ecommerce_client/models/sender_address'
require 'dhl_ecommerce_client/models/volume'
require 'dhl_ecommerce_client/models/weight'
require 'dhl_ecommerce_client/models/width'

# APIs
require 'dhl_ecommerce_client/api/authorization_api'
require 'dhl_ecommerce_client/api/duty_and_tax_calculator_api'

module DhlEcommerceClient
  class << self
    # Customize default settings for the SDK using block.
    #   DhlEcommerceClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
